name: life_flutter
description: "A Flutter app that manages my life."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path: ^1.9.1
  provider: ^6.1.5+1
  local_auth: ^3.0.0
  go_router: ^17.0.0
  flutter_launcher_icons: ^0.14.4
  logging: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/db/
    - assets/icon/

flutter_launcher_icons:
  image_path: 'assets/icon/icon.png'

  android: true
  ios: true

  adaptive_icon_background: '#FFFFFF'
  adaptive_icon_foreground: 'assets/icon/icon.png'
